version: '3.8'

services:
  mq:
    image: ibmcom/mq:latest
    container_name: hogan-mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      # Optional (if you want app/admin passwords):
      # MQ_ADMIN_PASSWORD: passw0rd
      # MQ_APP_PASSWORD: app12345
    ports:
      - "1414:1414"   # MQ listener
      - "9443:9443"   # MQ web console
    healthcheck:
      test: ["CMD-SHELL", "dspmq -o status | grep -q 'Running'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  bitcoind:
    image: bitcoin/bitcoin:latest
    container_name: hogan-bitcoind
    environment:
      BITCOIN_DATA: /data
    command: >
      bitcoind
      -regtest
      -txindex=1
      -fallbackfee=0.0002
      -rpcbind=0.0.0.0
      -rpcallowip=0.0.0.0/0
      -rpcuser=hoganuser
      -rpcpassword=hoganpass
      -zmqpubrawblock=tcp://0.0.0.0:28332
      -zmqpubrawtx=tcp://0.0.0.0:28333
      -deprecatedrpc=accounts
      -listen=1
      -server=1
      -printtoconsole=1
      -rpcport=18443
    ports:
      - "18443:18443"
      - "28332:28332"
      - "28333:28333"
    volumes:
      - bitcoin-data:/data
    networks:
      - hogan-net
    healthcheck:
      test: ["CMD", "bitcoin-cli", "-regtest", "-rpcuser=hoganuser", "-rpcpassword=hoganpass", "getblockchaininfo"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # MQ Configuration
  mq-config:
    image: ibmcom/mq:latest
    container_name: hogan-mq-config
    depends_on:
      mq:
        condition: service_healthy
    command: >
      sh -c "
        sleep 10 &&
        runmqsc QM1 < /config/queue_definitions.mqsc
      "
    volumes:
      - ./mq:/config
    networks:
      - hogan-net
    restart: "no"

volumes:
  mq-data:
    driver: local
  bitcoin-data:
    driver: local

networks:
  hogan-net:
    driver: bridge
