services:
  mq:
    image: ibmcom/mq:latest
    container_name: hogan-mq
    environment:
      LICENSE: accept
      MQ_QMGR_NAME: QM1
      # Optional (if you want app/admin passwords):
      # MQ_ADMIN_PASSWORD: passw0rd
      # MQ_APP_PASSWORD: app12345
    ports:
      - "1414:1414"   # MQ listener
      - "9443:9443"   # MQ web console
    healthcheck:
      test: ["CMD-SHELL", "dspmq -o status | grep -q 'Running'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 60s

  bitcoind:
      image: bitcoin/bitcoin:latest
      container_name: hogan-bitcoind
      command: >
        bitcoind -regtest=1 -txindex=1 -fallbackfee=0.0002 -rpcbind=0.0.0.0
                -rpcallowip=0.0.0.0/0 -rpcuser=bitcoin -rpcpassword=bitcoin
                -server=1 -printtoconsole=1 -rpcport=18443
      ports:
        - "18443:18443"
      healthcheck:
        test: ["CMD-SHELL", "bitcoin-cli -regtest -rpcuser=bitcoin -rpcpassword=bitcoin -rpcconnect=127.0.0.1 getblockcount >/dev/null 2>&1"]
        interval: 10s
        timeout: 5s
        retries: 30
        start_period: 20s